using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using PensionMCP.Data;

namespace TestPensionMCP.Data
{
    public class PensionDbContextTests
    {
        private SqliteConnection _connection;
        private PensionDbContext _context;

        [SetUp]
        public async Task SetUp()
        {
            _connection = new SqliteConnection("Data Source=:memory:");
            await _connection.OpenAsync();

            var options = new DbContextOptionsBuilder<PensionDbContext>()
                .UseSqlite(_connection)
                .Options;

            _context = new PensionDbContext(options);
            await _context.Database.EnsureCreatedAsync();
        }

        [TearDown]
        public void TearDown()
        {
            _context.Dispose();
            _connection.Dispose();
        }

        [Test]
        public async Task EnsureCreated_SeedsThreeClients()
        {
            var clients = await _context.Clients.ToListAsync();

            Assert.Multiple(() =>
            {
                Assert.That(clients, Has.Count.EqualTo(3));
                Assert.That(clients.Any(c => c.Name == "James Kirk"), Is.True);
                Assert.That(clients.Any(c => c.Name == "Nyota Uhura"), Is.True);
                Assert.That(clients.Any(c => c.Name == "Leonard McCoy"), Is.True);
            });
        }

        [Test]
        public async Task SeedDateOfBirth_SavedCorrectly()
        {
            var kirk = await _context.Clients.FirstAsync(c => c.Name == "James Kirk");

            Assert.That(kirk.DateOfBirth, Is.EqualTo(new DateOnly(1974, 12, 12)));
        }

        [Test]
        public async Task AddNewClient_CanBeRead()
        {
            var newClient = new PensionMCP.Models.Client
            {
                Name = "Spock",
                DateOfBirth = new DateOnly(1971, 1, 6)
            };
            _context.Clients.Add(newClient);
            await _context.SaveChangesAsync();

            var fetched = await _context.Clients.FirstOrDefaultAsync(c => c.Name == "Spock");

            Assert.That(fetched, Is.Not.Null);
            Assert.That(fetched!.DateOfBirth, Is.EqualTo(new DateOnly(1971, 1, 6)));
        }

        [Test]
        public async Task AddNewClient_IdIsAutoGenerated()
        {
            var newClient = new PensionMCP.Models.Client
            {
                Name = "Hikaru Sulu",
                DateOfBirth = new DateOnly(2004, 3, 15)
            };

            Assert.That(newClient.Id, Is.EqualTo(0));

            _context.Clients.Add(newClient);
            await _context.SaveChangesAsync();

            Assert.That(newClient.Id, Is.GreaterThan(0));
        }
    }
}