// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionMCP.Data;

#nullable disable

namespace PensionMCP.Migrations
{
    [DbContext(typeof(PensionDbContext))]
    [Migration("20260424204157_NewDB")]
    partial class NewDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PensionMCP.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1974, 12, 12),
                            Name = "James Kirk"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1982, 7, 25),
                            Name = "Nyota Uhura"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1990, 11, 1),
                            Name = "Leonard McCoy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
