// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionMCP.Data;

#nullable disable

namespace PensionMCP.Migrations
{
    [DbContext(typeof(PensionDbContext))]
    [Migration("20260426145825_FR003TaxRelief")]
    partial class FR003TaxRelief
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PensionMCP.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentMonthlyEmployersContribution")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentMonthlyPensionContribution")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPensionPotValue")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsQualifyingSingleParent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetRelevantIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpouseIncome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentMonthlyEmployersContribution = 1000m,
                            CurrentMonthlyPensionContribution = 1000m,
                            CurrentPensionPotValue = 100000m,
                            DateOfBirth = new DateOnly(1974, 12, 12),
                            IsMarried = false,
                            IsQualifyingSingleParent = false,
                            Name = "James Kirk",
                            NetRelevantIncome = 44000m,
                            SpouseIncome = -1m
                        },
                        new
                        {
                            Id = 2,
                            CurrentMonthlyEmployersContribution = -1m,
                            CurrentMonthlyPensionContribution = -1m,
                            CurrentPensionPotValue = -1m,
                            DateOfBirth = new DateOnly(1982, 7, 25),
                            IsMarried = true,
                            IsQualifyingSingleParent = false,
                            Name = "Nyota Uhura",
                            NetRelevantIncome = 45000m,
                            SpouseIncome = 30000m
                        },
                        new
                        {
                            Id = 3,
                            CurrentMonthlyEmployersContribution = -1m,
                            CurrentMonthlyPensionContribution = -1m,
                            CurrentPensionPotValue = -1m,
                            DateOfBirth = new DateOnly(1990, 11, 1),
                            IsMarried = false,
                            IsQualifyingSingleParent = false,
                            Name = "Leonard McCoy",
                            NetRelevantIncome = 120000m,
                            SpouseIncome = -1m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
