
name: CI
env:
  DOTNET_VERSION: 10.0.x
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "EoinPerm*" ]
      
  workflow_dispatch:

permissions:
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  job-unit-test:
    uses: ./.github/workflows/reusable-unittests.yml
  
  job-build-windows-exe:
    needs: job-unit-test
    uses: ./.github/workflows/reusable-build-windows-exe.yml

  job-lint:
    needs: job-build-windows-exe
    uses: ./.github/workflows/reusable-lint.yml

  