name: Generate and Publish Docs

on:
  push:
    branches:
      - EoinDocs*
    tags:
      - 'r*'
  workflow_dispatch:

jobs:
  # see docs  https://dotnet.github.io/docfx/
  job-build-docs:
    name: Build DocFX Site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v6.0.2


      - uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: 10.0.x

      - run: dotnet tool install --global docfx

      - run: docfx docfx.json

      - uses: actions/upload-pages-artifact@v5
        with:
          path: _site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5