name: dora
on:
  workflow_call:
  workflow_dispatch:

  #schedule:
  #  - cron: '0 23 * * *' # everday at 11pm
  #    timezone: "Europe/Dublin"

jobs:
  dora-deployment-frequency: 
    runs-on: ubuntu-latest


    steps:
      # https://github.com/marketplace/actions/dora-deployment-frequency
      - uses: DeveloperMetrics/deployment-frequency@v1.5.22
        with:
          workflows: 'Build-Installer'
          actions-token: ${{ secrets.GITHUB_TOKEN }}


 