name: Create SBOM
on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-sbom: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-dotnet@v5.2.0
        with:
            dotnet-version: 10.0.x
      - run: dotnet tool install --global CycloneDX
      - run: dotnet-CycloneDX ./PensionMCP/PensionMCP.csproj -o ./
      - uses: actions/upload-artifact@v7.0.1 
        with:
          name: bom.xml
          path: ./bom.xml