name: Lint Changes
on:
  workflow_call:
  push:
    branches: [ "EoinLint*" ]

jobs:
  lint-changes: 
    runs-on: ubuntu-latest

    steps:
      
      # superlinter needs the main branch to be able to do comparison 
      - name: Checkout main
        uses: actions/checkout@v6.0.2
        with:
          ref: main

      - name: Checkout the current branch
        uses: actions/checkout@v6.0.2
        

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_EDITORCONFIG: true
          VALIDATE_CSHARP: true
          DEFAULT_BRANCH: main