name: Build Windows PensionMCP
on:
  workflow_call:

permissions:
      # only required for workflows in private repositories
      actions: read
      contents: read

jobs:
  JobBuildWindowsExe:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6.0.2
        - name: Setup .NET
          uses: actions/setup-dotnet@v5.2.0
          with:
            dotnet-version: ${{env.DOTNET_VERSION}}
            cache: true
            cache-dependency-path: '**/packages.lock.json'
        - name: Build Windows PensionMCP EXE
          run: dotnet publish ./PensionMCP/PensionMCP.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish
        - name: Upload EXE artifact
          uses: actions/upload-artifact@v7.0.1             
          with:
            #archive: false # new feature, but my artefacts are quiet large.
            name: PensionMCP.exe.zip
            path: ./publish/PensionMCP.exe
            retention-days: 1 # spotted in docs, can set in yml rather than GitHub UI